[package]
name = "k3_aiRuntime"
version = "0.1.0"
edition = "2024"

[lib]
name = "k3_ai_runtime"
crate-type = ["rlib", "staticlib"]

[features]
default = []
host-cpu = ["dep:k3_kernel_backend"]

[dependencies]
lazy_static = "1.5.0"
ov-channels = { version = "0.2" }
k3_aiUabi = { path = "../k3_aiUabi" }
k3_kernel_backend = { path = "../k3_kernel_backend", optional = true }
